# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: zzyang
instance_flavor: uom.mse.1c4g
instance_network: qh2-uom
inventory_dir: inventory/inventory.ini

# Docker vars
dockerhub_username: zzyang1994
dockerhub_token: 651bc8ae-1e36-4e88-a112-868599ad9908
dockerhub_email: yangzhanzhao1994@gmail.com
docker_image: zzyang1994/cccproj2:backend

# Volume
volumes:
  - vol_name: backend-test-vol
    vol_size: 10

# Security group
security_groups:
  - name: backend_test_ssh
    description: "Frontend security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: backend_test_http
    description: "Frontend security group for HTTP"
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: backend-test
    volumes: ['backend-test-vol']

