---
# Install dependencies on the host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update && sudo apt-get install python3-dev python3-setuptools python-pip

- name: Update pip
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest
# pip install --upgrade pip && pip install openstacksdk

# Install Docker
- name: install prerequisites
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates 
      - curl 
      - gnupg-agent
      - software-properties-common
    update_cache: yes

- name: add apt-key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add docker repo
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: install docker 
  become: yes
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: add userpermissions
  become: yes
  shell: "usermod -aG docker {{ lookup('env','USER') }}"

- name: install python sdk
  become: yes
  become_user: "{{ lookup('env','USER') }}"
  pip:
    name:
      - docker
      - docker-compose