---
- hosts: localhost
  vars_files:
    - host_vars/backend-vars.yaml
  gather_facts: true
  roles:
    - role: common
    - role: volume
    - role: security-group
    - role: instance

- hosts: all
  vars_files:
    - host_vars/backend-vars.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/test01privatekey.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
      - role: common
        when: ansible_hostname == "backend-test"
      - role: remove-previous-image
        when: ansible_hostname == "backend-test"
      - role: docker-login
        when: ansible_hostname == "backend-test"
      - role: docker-pull-and-run
        when: ansible_hostname == "backend-test"
      - role: docker-logout
        when: ansible_hostname == "backend-test"